# Generated by Django 2.2.7 on 2020-02-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewData',
        ),
    ]
