# Generated by Django 2.2.7 on 2020-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_delete_reviewdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=50)),
                ('star', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
