# Generated by Django 2.2.7 on 2020-02-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_reviewdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Building')),
            ],
        ),
        migrations.RemoveField(
            model_name='reviewdata',
            name='prof',
        ),
        migrations.AddField(
            model_name='reviewdata',
            name='review',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reviewdata',
            name='coursename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Course'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Major')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Professor'),
        ),
    ]
