# Generated by Django 2.2.7 on 2020-02-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200224_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Major'),
        ),
    ]
