# Generated by Django 2.2.7 on 2020-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20200224_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCrawlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingnum', models.CharField(max_length=20)),
                ('profname', models.CharField(max_length=20)),
                ('coursename', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
